name: Terraform Security Scan with Checkov

on:
  push:
    branches: [ master ]
  
jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target Terraform repository
        run: |
          git clone https://github.com/octodemo/advanced-security-terraform.git repo
           
          echo " Repository cloned successfully"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Checkov and jq
        run: | 
          pip install checkov
          sudo apt-get update -y
          sudo apt-get install -y 

      - name: Run Checkov scan on cloned repo
        run: |
           checkov --directory  repo/terraform \         
           --output json \
           --compact \
           --soft-fail > repo/checkov_output.json || true
           
            
      - name: Upload Checkov reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-reports
          path: repo/checkov_output.json 

      - name: Send Checkov report to DefectDojo
        run: |
          echo " Uploading report to DefectDojo..."
          curl -X POST "${{ secrets.DEFECTDOJO_HOST }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "scan_type=Checkov Scan" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            -F "file=@repo/checkov_output.json" \
            -F "active=true" \
            -F "verified=true" \
            -F "minimum_severity=Info" \
            -F "auto_create_context=true"
